config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' } #:path_names => { :new => 'make', :edit => 'change' }
  resources :portfolios
  resources :comments

  root to: 'pages#home'
  get 'pages/home'
  get 'about-me', to: 'pages#about'  
  get 'contact', to: 'pages#contact'
  # get 'technlogy', to: 'portfolios#technlogy'


  resources :blogs do
  	member do
  		get :toggle_status
  		
  	end
  end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status:{draft: 0, published: 1} #added for enum action
	extend FriendlyId
	friendly_id :title, use: :slugged  #title ko slug banauna ko lagi name lai title le replace garya
	validates_presence_of :title, :body #to validate the data

	belongs_to :topic, optional: true
	belongs_to :user
	has_many :comments, :dependent => :destroy

	after_create -> (model) { model.update(status: 0) }  #used for default status draft after creation

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action only: [:show, :update, :destroy]
  before_action :set_blog
  # layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.friendly.find(params[:id])
    #edited for friendly id to make slug to the url
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /blogs/1/edit
  def edit
      @blog = Blog.find_by(slug: params[:id])
       authorize! :edit, @blog
  end

  # POST /blogs
  # POST /blogs.json
  def create


 
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else

    if can? :create, Blog

      @blog = Blog.new(blog_params)
      @blog.user_id = current_user.id   #user id defined for blog
      @created_blog = @blog
      respond_to do |format|
        if @blog.save
          format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
          format.js
          
        else
          format.html { render :new }
          format.js
          #format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        #format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    
      @blog.destroy
      respond_to do |format|
        format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      end
    
  end
      
  

def toggle_status   #this is for update publish or draft of the items
  respond_to do |format|
      @blog = Blog.find_by(slug: params[:id])
      if @blog.status == "draft"
        @blog.update(status: :published)
        format.js
      else
        @blog.update(status: :draft)
        format.js
      end
      format.html{redirect_to blogs_url, notice: 'post has successufully updated'}
  end
  #byebug
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      #@blog = Blog.find(params[:id])
      @blog = Blog.find_by(slug: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_comments.html.erb
    
    <div class="col-md-6 comments-property" id="blog-comment-<%= blog.id %>">
      <% blog.comments.each do |a|%>
      <div class="container border border-white" >
        <div class="card-header"><%= image_tag gravatar_url("you@youremail.com", 30), alt: "", :style => "margin-right: 5px;" %><%= User.find(a.user_id).name %></div>
        <div class="card-body" id="comment-<%= a.id%>"><%= a.text %></div>
        <p style="margin-left: 40px;" id="comment-links-<%=a.id%>">
          <% if a.user_id == current_user.id%>
          <%= link_to "Edit", edit_comment_path(a), class: "btn btn-info btn-sm" , remote: true %>
          <% end %>
          <% if a.user_id == current_user.id%>
          <%= link_to "Delete", a, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", :remote => true, :id => 'delete_comment_#{a.id}' %>
          <%end%>
        </p>
        </div>

        <% end %>
      </div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, class: 'row') do |form| %>
 
  <% if blog.errors.any? %>
  <div class="row">
    <div class="col-md-4" style="background-color: dark"></div>
    <div class="col-md-4">
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
  <% end %>
      </ul>
    </div>
    <div class="col-md-4"></div>
  </div>

  <% end %>
 <div style="background-color: dark">
  <div class="row">
     <div class="col-md-2"></div>
     <div class="col-md-1"><%= form.label :title %></div>
     <div class="col-md-8"><%= form.text_field :title, class: "form-control", rows: 25 %></div>
     <div class="col-md-1"></div>
      
  </div>
  <hr>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-1"><%= form.label :body %></div>
    <div class="col-md-9">
      <%= form.hidden_field :body, id: :post_body, class: "form-control-lg"%>
      <trix-editor input="post_body" ></trix-editor> 
      </div>
   
  </div>
  <hr>
<!--   <input id="x" type="hidden" name="content">
  <trix-editor input="x"></trix-editor> -->
   


  <div class="row">
    <div class="col-md-10"></div>
    <div class="col-md-1 "><%= form.submit "Post", class: "btn btn-success" %></div>
    <div class="col-md-1"></div>
  </div>
</div>

<% end %>

app/views/blogs/_formForAppend.html.erb
<% blog = @created_blog %>
<% if (current_user.name == "admin" and  blog.status == "draft" ) or (blog.status == "published" )%>
<div class="card"><br>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-7 card-header" style="font-size:3vw">
     <%= blog.title %>
   </div>
   <div class="col-md-2"></div>
 </div>

 <div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-5">
    <i class="fas fa-pen-nib 3x"></i>
    <i style="color: #8B008B;"><strong><%= User.find(blog.user_id).name %></strong></i></div>
    <div class="col-md-4"></div>
  </div>

  <div class="row ">
    <div class="col-md-3"></div>
    <div class="col-md-7 ">
     <div id="truncated-blog-body-<%= blog.id%>" style="display: block;">
      <% if blog.body.length > 250 %>
      <%= sanitize(blog.body.truncate(580, separator: '')) %>
      <p>
        <%# link_to '...Read more', '', class: "read-more-#{blog.id}"  %>
        <a href="#", id="read-more-<%= blog.id%>" onClick="readMore(event,<%= blog.id %>)" >read more</a>
      </p>
      <script>

      </script>
      <% else %>
      <%= sanitize blog.body %>
      <% end %>
    </div>
    <div id="blog-body-<%= blog.id%>" style="display: none;" ><%= sanitize(blog.body) %></div>

  </div>
  <div class="col-md-2 ">
   <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago 
 </div>
 <!-- for date of publish of each items calculation -->
</div>


<div class="row">
  <div class="col-md-3"></div>

  <div class="col-md-1 far fa-comment-alt fa-3x" id = "button-comment-<%= blog.id%> "  style="margin-left:10px; color: blue;" onClick="commentsShow(<%= blog.id %>)"></div>


  <div class="col-md-1" >
    <% if blog.user_id == current_user.id%>
    <%= link_to  edit_blog_path(blog), class: "btn btn-primary", style: "margin-left:-36px;" do %>
    <i class="far fa-edit fa-2x"></i>
    <%end%>
    <%end%>
  </div>

  <div class="col-md-1">

    <% if can? :destroy, blog %>
         <%= link_to  blog, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-primary", style: "margin-left:-65px;" do %>
        <i class="fas fa-trash-alt fa-2x"></i>
    
    <% end %>
    <%end%>

  </div>

  <div class="col-md-1">
    <% if can? :status, blog %>
    <%= link_to blog.status, toggle_status_blog_path(blog), class: "btn btn-primary", style: "margin-left:-103px" %>
    <% end %>
  </div>
  <div class="col-md-6"></div>
</div>

<div id="bind-comments-<%= blog.id%>" class="comments-area">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <% if user_signed_in? %>
      <%= render :partial => 'comments/newcomment', locals: {blog_id: blog.id} %>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
  <div class="row">
    <div class="col-md-3"></div>
    <% if blog.comments.exists? %>
    <div class="col-md-6 comments-property">
      <% blog.comments.each do |a|%>
      <div class="container border border-white">
        <div class="card-header"><%= image_tag gravatar_url("you@youremail.com", 30), alt: "", :style => "margin-right: 5px;" %><%= User.find(a.user_id).name %></div>
        <div class="card-body"><%= a.text %></div>
        <p style="margin-left: 40px;">
          <% if a.user_id == current_user.id%>
          <%= link_to "Edit", edit_comment_path(a), class: "btn btn-info btn-sm" %>
          <% end %>
          <% if a.user_id == current_user.id%>
          <%= link_to "Delete", a, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
          <%end%>
        </div>

        <% end %>
      </div>
      <% end %>
      <div class="col-md-3"></div>
    </div>
  </div><br>
</div>
<% end %><br>

app/views/blogs/_formIndex.html.erb
<% @blogs.each  do |blog| %>
<% if (current_user.name == "admin" and  blog.status == "draft" ) or (blog.status == "published" )%>
<div class="card"><br>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-7 card-header" style="font-size:3vw">
     <%= blog.title %>
   </div>
   <div class="col-md-2"></div>
 </div>

 <div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-5">
    <i class="fas fa-pen-nib 3x"></i>
    <i style="color: #8B008B;"><strong><%= User.find(blog.user_id).name %></strong></i></div>
    <div class="col-md-4"></div>
  </div>

  <div class="row ">
    <div class="col-md-3"></div>
    <div class="col-md-7 ">
     <div id="truncated-blog-body-<%= blog.id%>" style="display: block;">
      <% if blog.body.length > 250 %>
      <%= sanitize(blog.body.truncate(580, separator: '')) %>
      <p>
        <a href="#", id="read-more-<%=blog.id%>" onClick="readMore(event,<%= blog.id %>)" >read more</a>
      </p>

      <% else %>
      <%= sanitize blog.body %>
      <% end %>
    </div>
    <div id="blog-body-<%=blog.id%>" style="display: none;" ><%= sanitize(blog.body) %></div>

  </div>
  <div class="col-md-2 ">
   <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago 
 </div>
 <!-- for date of publish of each items calculation -->
</div>


<div class="row">
  <div class="col-md-3"></div>

  <div class="col-md-1 far fa-comment-alt fa-3x" id = "button-comment-<%= blog.id%> "  style="margin-left:10px; color: blue;" onClick="commentsShow(<%= blog.id %>)"></div>


  <div class="col-md-1" >
    <% if blog.user_id == current_user.id%>
    <%= link_to  edit_blog_path(blog), class: "btn btn-primary", style: "margin-left:-36px;" do %>
    <i class="far fa-edit fa-2x"></i>
    <%end%>
    <%end%>
  </div>

  <div class="col-md-1">

    <% if can? :destroy, blog %>
         <%= link_to  blog, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-primary", style: "margin-left:-65px;" do %>
        <i class="fas fa-trash-alt fa-2x"></i>
    
    <% end %>
    <%end%>

  </div>

  <div class="col-md-1">
    <% if can? :status, blog %>
    <%= link_to blog.status, toggle_status_blog_path(blog),id: "status-blog-#{blog.id}", class: "btn btn-primary", style: "margin-left:-103px", remote:true%>
    <% end %>
  </div>
  <div class="col-md-6"></div>
</div>

<div id="bind-comments-<%= blog.id%>" class="comments-area">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <% if user_signed_in? %>
      <%= render :partial => 'comments/newcomment', locals: {blog_id: blog.id} %>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
  <div class="row">
    <div class="col-md-3"></div>
    <% if blog.comments.exists? %>
     <%= render :partial => "comments", locals: { blog: blog} %>
      <% end %>
      <div class="col-md-3"></div>
    </div>
  </div><br>
</div>
<% end %><br>
<% end %>

app/views/blogs/_newModal.html.erb
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" style="margin-left: 284px;">create new blog</h4>
          <button type="button" class="close" data-dismiss="modal" >&times;</button>
          
        </div>
        <div class="modal-body">
          <%= form_with(model: blog = Blog.new, remote: true, class: 'row') do |form| %>


          <% if blog.errors.any? %>
          <div class="row">
            <div class="col-md-4" style="background-color: dark"></div>
            <div class="col-md-4">
              <div id="error_explanation">
                <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

                <ul>
                  <% blog.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
              <div class="col-md-4"></div>
            </div>
          </div>

          <% end %>
          <div style="background-color: dark">
            <div class="row">
             <div class="col-md-2"><%# form.label :title %></div>
             <div class="col-md-11"><%= form.text_field :title, {:class=>"form-control form-control-lg", :style=>"margin-left:80px;", :placeholder=>"Enter title of your blog", id: :post_title }%>
             </div>

           </div>
           <hr>

           <div class="row">
            <div class="col-md-2"><%#= form.label :body %></div>
            <div class="col-md-10">
              <%= form.hidden_field :body, id: :post_body %>
              <trix-editor input="post_body", placeholder="enter blog body", class:"form-control-lg", style="margin-right: 3px; overflow: scroll;" ></trix-editor> 
            </div>

          </div>
          <hr>
<!--   <input id="x" type="hidden" name="content">
  <trix-editor input="x"></trix-editor> -->



  <div class="row">
    <div class="col-md-10"></div>
    <div class="col-md-1 "><%= form.submit "Post", class: "btn btn-success" %></div>
    <div class="col-md-1"></div>
  </div>
</div>

<% end %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
</div>
</div>
</div>

app/views/blogs/create.js.erb
$('#myModal').modal('hide');
$('#post_title').val('');
$('#post_body').val('');
$('.blogs-container').prepend("<%= j render 'formForAppend', locals: { blog:@created_blog } %>");

app/views/blogs/edit.html.erb
<div class="card">
	<div class="card-body">
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-6"><h3>Edit your Blog</h3></div>
			<div class="col-md-2"></div>
		</div>
		<hr>
		<div>

			<%= render 'form', blog: @blog %>

	        <div class="row button-edit-blog button-edit-blog">
	          <div class="col-md-3"></div>
	          <div class="col-md-1">
	          	<%= link_to 'Show', @blog, class: "btn btn-dark" %>
	          </div>
	          <div class="col-md-1"><%= link_to 'Back', blogs_path, class: "btn btn-secondary" %>
	          	
	          </div>
	          <div class="col-md-7"></div>

	          </div>
	      </div>
	</div>
		
			 
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="row">
   <!--  <div class="col-md-1"></div> -->
   <div class="col-md-2">
    <% if can? :create, Blog %>
    <%= link_to 'New Blog', new_blog_path, :class =>"btn btn-primary", :remote => true, "data-toggle" => "modal", "data-target" => "myModal", :id => "new-blog-link" %>
    <!--<a href="/blogs/new"  class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal">New blog</a> -->
    <% end %>
    <%= render 'newModal' %>
  </div>
  <div class="col-md-10"></div>

</div>
<div class="blogs-container">
<% if user_signed_in?%>
  <%= render "formIndex" %>
<%end%>
</div>
</div>

app/views/blogs/new.html.erb
<div class="card" style="width: 100%;">
	<div class="card-body">
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-9"><h5>Create your New Blog here...</h5></div>

		</div>
		<%= render 'form', blog: @blog %>
		
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-1"><%= link_to 'Back', blogs_path, class: "btn btn-primary" %></div>
			<div class="col-md-9"></div>

		</div>
	</div>

</div>

app/views/blogs/new.js.erb
$('#myModal').modal('show');

app/views/blogs/show.html.erb
<div class="container"></div>
<p id="notice"><%= notice %></p>
<div class="col-md-7 border rounded" style="background-color: white ">
	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-6">
			<!-- <strong>Blog Title:</strong> -->
		</div>
		<div class="col-md-3">
		</div>
	</div>
	<div class="row" >
		<div class="col-md-3"></div>
		<div class="col-md-7">
			<strong style="font-size:30px"><%= @blog.title %></strong>
		</div>
		<div class="col-md-2"></div>
	</div>
	<hr>

	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-7">
			<!-- <strong>Blog Body:</strong> -->
		</div>
		<div class="col-md-2"></div>
	</div>

	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-7">
			<%= sanitize @blog.body %>
		</div>
		<div class="col-md-2"></div>
	</div>

   <div class="row button-show-blog btn-toolbar">
	<% if can? :edit, Blog %>
	<div class="col-md-3"></div>
		<div class="col-md-2 btn btn-dark">
		 <%= link_to 'Edit', edit_blog_path(@blog) %> 
		</div>
	    
		<div class="col-md-2 btn btn-dark">
			<%= link_to 'Back', blogs_path %>
		</div>
		<div class="col-md-5"></div>
	  <!-- </div> -->


	<% end %>

	
   </div>
</div> 

app/views/blogs/toggle_status.js.erb
 
 function status(id){
 	if(document.getElementById(`status-blog-${id}`).innerHTML === 'draft'){
 		document.getElementById(`status-blog-${id}`).innerHTML = 'published'
 	}
 	else{
 		document.getElementById(`status-blog-${id}`).innerHTML = 'draft'
 	}
 }
status(<%= @blog.id%>);
//button ma rakhda first mai status function call vayekole this toggle_status.js.erb ma call garya
// $(document).ready(function(){
//     $('.status-blog-<%=@blog.id%>').on('click', function() {
//     	debugger
//       if ( this.value == 'draft')
//       {
//         $(".status-blog-<%=@blog.id%>").innerHTML('Published');
//       }
//       else
//       {
//         $(".status-blog-<%=@blog.id%>").innerHTML('Draft');
//       }
//     });
// });