config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' } #:path_names => { :new => 'make', :edit => 'change' }
  resources :portfolios
  resources :comments

  root to: 'pages#home'
  get 'pages/home'
  get 'about-me', to: 'pages#about'  
  get 'contact', to: 'pages#contact'
  # get 'technlogy', to: 'portfolios#technlogy'


  resources :blogs do
  	member do
  		get :toggle_status
  		
  	end
  end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/shared_by_all/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
      	<%= link_to "About", about_me_path , class: 'nav-link'%>
      </li>
        <li class="nav-item">
      	<%= link_to "Contact", contact_path , class: 'nav-link' %>
      </li>
      <li class="nav-item">
      	<%= link_to "Blog", blogs_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
      	<%= link_to "Portfolio", portfolios_path , class: 'nav-link'%>
      </li>
    
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
     <ul class="navbar-nav mr-auto">
     	<li class="nav-item">
     		<% if user_signed_in?%>	
     			<%= link_to "logout", destroy_user_session_path, method: :delete, class: 'btn btn-danger'%>
     		<%else%>
     			<%= link_to "login", new_user_session_path, class: 'btn btn-success'%>
          <%= link_to "register", new_user_registration_path, class: 'btn btn-primary'%>
     		<%end%>
      </li>
     </ul> 
  </div>
</nav>