config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' } #:path_names => { :new => 'make', :edit => 'change' }
  resources :portfolios
  resources :comments

  root to: 'pages#home'
  get 'pages/home'
  get 'about-me', to: 'pages#about'  
  get 'contact', to: 'pages#contact'
  # get 'technlogy', to: 'portfolios#technlogy'


  resources :blogs do
  	member do
  		get :toggle_status
  		
  	end
  end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
# frozen_string_literal: true

# models are defined here
class Portfolio < ApplicationRecord
  has_attached_file :main_image, styles: { large: "800x800", medium: "800x800>", thumb: "100x100#" }, default_url: "DefaultImage.png"
  # default_url: "/images/:style/missing.png"
  validates_attachment_content_type :main_image, content_type: /\Aimage\/.*\z/

  has_many :technlogies,
  dependent: :destroy  #this is for destroy all the dependencies for all portfolio items

  accepts_nested_attributes_for :technlogies,  #this two lines are for validation of nested items of technlogies on form
    reject_if: proc {|x|  x['name'].blank?}

  validates_presence_of :title, :body 

  after_initialize :set_defaults  #method to initialize the portfolio items with default placeholder
  scope :python, -> {where(title: 'python')}	

	# def self.python 
	# 	where(title: 'python')}
	# end
  def set_defaults
    self.main_image ||= 'https://via.placeholder.com/550x250'
  # self.thumb_image ||= 'https://via.placeholder.com/150x50'
  end
end

app/controllers/portfolios_controller.rb
# frozen_string_literal: true

# actions related to portfolios are defined here
class PortfoliosController < ApplicationController
  respond_to :html, :js
  # layout 'portfolio'

  def index 

    if can? :create, Portfolio
      @portfolio_items_new = Portfolio.new
      3.times { @portfolio_items_new.technlogies.build }
    end
      if params[:name]
       @portfolio_items = []
       @tec=Technlogy.all.where(name: params[:name])
       @tec.each do |x|
        @portfolio_items << x.portfolio
      end
    else
      @portfolio_items = Portfolio.all
    end

  @name_of_tech = (Technlogy.all.map { |x| x.name}).uniq 
    #finds all the technlogy used
  end

  def new
    if can? :create, Portfolio
      @portfolio_items = Portfolio.new
      3.times { @portfolio_items.technlogies.build }
    else
      redirect_to root_path
    end
  end

  def create
    if can? :create, Portfolio
      @portfolio_items = Portfolio.new(portfolio_items)
      if @portfolio_items.save
        @latest_item = Portfolio.last
        flash[:notice] = 'New portfolio item is successfully created'
        redirect_to portfolios_path
      else
        x.html { render :new }
      end
    end
  end

  def edit
    if can? :edit, Portfolio
      @portfolio_items = Portfolio.find(params[:id])
    else
      redirect_to portfolios_path
    end
  end

  def update
    if can? :update, Portfolio
      @portfolio_items = Portfolio.find(params[:id])
      if @portfolio_items.update_attributes(portfolio_items)
        redirect_to portfolios_path
      else
        render 'edit'
      end
    end
  end

  def show
    @portfolio_items = Portfolio.find(params[:id])
  end

  def destroy
    if can? :destroy, Portfolio
      @portfolio_items = Portfolio.find(params[:id])
      @portfolio_items.destroy
      redirect_to portfolios_path
    end
  end


  private

  def portfolio_items
    params.require(:portfolio).permit(
     :title, :subtitle, :body, :main_image,
     technlogies_attributes: [:id, :name]
     )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_formportfolionew.html.erb
<div id="form_ajax">
<%= form_for @portfolio_items, html: { multipart: true }, remote: true do |a| %> <!--for new portfolio item bug fixe-->
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-7"><h2>create new portfolio here:</h2></div>
  <div class="col-md-1"></div>
</div>


<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-6"> <%= a.label :title %></div>
  <div class="col-md-2"></div>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-6">
    <%= a.text_field :title, class: "form-control" %>
 </div>
 <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-6"> <%= a.label :subtitle %></div>
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-6">
      <%= a.text_field :subtitle, class: "form-control" %>
  </div>
  <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-6">
     <%= a.label :body %>
 </div>
 <div class="col-md-2"></div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-2">
   
  </div>
  <div class="col-md-6">
    <%= a.text_area :body, class: "form-control"  %>
  </div>
  <div class="col-md-2"></div>
</div><br>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-6"><h5> Main Technlogies used for this portfolio:</h5></div>
  <div class="col-md-2"></div>

</div>



 <!--this form is for technlogy names-->
    
   <%= a.fields_for :technlogies do |technlogy_form| %>  
<div class="row">
  <div class="col-md-5"></div>
  <div class="col-md-4">
    <div class="row">
      
        <%= technlogy_form.label :technlogy %>
    </div>
    <div class="row">
          <%= technlogy_form.text_field :name, class: "form-control input-sm" %>
         <%= technlogy_form.hidden_field :id%> 
    </div>
  </div>
  <div class="col-md-2"></div>
</div>

    <% end %>
    <br>
 <div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-6">
    <%= a.file_field :main_image %>
  </div>
  <div class="col-md-2"></div>
</div>
    <br>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-6">
        <%= a.submit "create", class: "btn btn-success", style: "margin-left: 70px;" %>
       </div>
       <div class="col-md-2"></div>
    </div>

<% end %>
</div>

app/views/portfolios/_new.html.erb
<div id="form_ajax">
	<%= form_with model: @portfolio_items_new ,url: portfolios_path, remote: true do |a| %> <!--for new portfolio item bug fixe-->

	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-6"> <%= a.label :title %></div>
		<div class="col-md-2"></div>
	</div>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-6">
			<%= a.text_field :title, class: "form-control" %>
		</div>
		<div class="col-md-2"></div>
	</div>

	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-6">
			<%= a.label :about %>
		</div>
		<div class="col-md-2"></div>
	</div>

	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-2">

		</div>
		<div class="col-md-6">
			<%= a.text_area :body, class: "form-control", placeholder: "Enter description of portfolio"   %>
		</div>
		<div class="col-md-2"></div>
	</div><br>

	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-6"><h5> Main Technlogies used for this portfolio:</h5></div>
		<div class="col-md-2"></div>

	</div>



	<!--this form is for technlogy names-->
	<%= a.fields_for :technlogies do |technlogy_form| %>  
	<div class="row">
		<div class="col-md-5"></div>
		<div class="col-md-4">
			<div class="row">

				<%#= technlogy_form.label :technlogy %>
			</div>
			<div class="row">
				<%= technlogy_form.select :name, ['Python', 'Ruby', 'Java'], {:prompt => "none"}, :id => 'cmbTaxID'%>
				<%= technlogy_form.hidden_field :id %>  

			</div>
		</div>
		<div class="col-md-2"></div>
	</div><br>
	<% end %>
	<br> 
    <div class="row">
    	<div class="col-md-4"></div>
    	<div class="col-md-6">Enter main design echnlogy(if any?)</div>
    	<div class="col-md-2"></div>
    </div>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-6">
			<%= a.text_field :subtitle, class: "form-control new-portfolio-modal-subtitle", placeholder: "If more than one separate by add sign (+)" %>
		</div>
		<div class="col-md-2"></div>
	</div><br>

	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-6">
			<%= a.file_field :main_image %>
		</div>
		<div class="col-md-2"></div>
	</div>
	<br>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-6">
			<%= a.submit "create", class: "btn btn-success", style: "margin-left: 70px;" %>
		</div>
		<div class="col-md-2"></div>
	</div>

	<% end %>
</div>

app/views/portfolios/_newPortfolioModal.html.erb
<%if can? :create, Portfolio %>
<button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal", remote: true >New portfolio</button>

<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header" style="margin-left: 250px; margin-right: 150px;">
				<h4 class="modal-title">Create your new item here:</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<%= render "new"%>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/portfolios/_showPortfolioModal.html.erb
<div class="modal fade" id="myModalitems-<%=itemid%>" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="modal-header-portfolio-<%=itemid%>">Modal Header</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="modal-body body-tag-in-portfolio-modal" >
        <p id="modal-body-portfolio-<%=itemid%>">body of portfolio</p>
      </div>

      <div style="text-align: center;"> Main Design technologies:
        <h5 id="modal-body-subtitle-<%=itemid%>" class="subtitle-inside-modal" >this is field for more tech used</h5>
      </div> 

      <div id="modal-image-portfolio-<%=itemid%>">image</div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_showTEST.html.erb
<% @portfolio_items.each  do |item| %>
<div class="card"><br>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-4">
			<h3><%=link_to item.title, portfolio_path(item.id), class: "card-title" %> </h3> <!--this is for we have to make the link the title attribute of each portfolio item to show page-->
		</div>
		<div class="col-md-6"></div>
	</div>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-6">
			<h4><i><%= item.subtitle %></i></h4>
		</div>
		<div class="col-md-4"></div>
	</div>

	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-4"><h5> for more about this item click here:</h5></div>
		<div class="col-md-1">
			<button class="btn btn-primary btn-sm" id="show-<%=item.id%>" onClick="seeMore(<%= item.id%>)">show</button>
		</div>
		<div class="col-md-1">

		
		<div class="col-md-4"></div>
	</div>

	<div class="row">
		<div class="col-md-2 " id="" ></div>
		<div class="col-md-8">
			<p class="mydiv" id="item-body-<%=item.id%>"><%= item.body%>
				<button class="btn btn-primary btn-sm" id="hide-<%=item.id%>" onClick="seeLess(<%= item.id%>)">hide</button>

			</p>
		</div>

		<div class="col-md-2"></div>
	</div>


	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-6">
			<%= image_tag item.main_image.url, class: "card-img-top", style:alt="Card image cap"  %> 

		</div>
		<div class="col-md-4"></div>
	</div><br>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-1" >
			<%if can? :edit, Portfolio%>
			<%= link_to "Edit", edit_portfolio_path(item.id), class: "btn btn-secondary", style: "margin-left: 35px;" %>  <!--for edit each post -->
			<%end%>
		</div>
		<div class="col-md-1">
			<%if can? :delete, Portfolio%>
			<%= link_to 'Delete',"/portfolios/#{item.id}",method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-secondary", style: "margin-left: 2px;"%>
			<%end%>
		</div>
		<div class="col-md-8"></div>
	</div><br>
	<% end %>
	<% end %>
</div>

app/views/portfolios/_showitem.html.erb
<div class="container portfolio-items" style="background-color: white;"><br>
	<div class="row">
		<div class="col-md-2" id="thismodel"></div>
		<div class="col-md-2"><%= link_to "All Items", portfolios_path %></div>
		<div class="col-md-2">
			<%= link_to "Python Items", { :controller => 'portfolios', :action => 'index', :name => 'Python'} %>              
		</div>

		<div class="col-md-2"><%= link_to "Ruby Items", { :controller => 'portfolios', :action => 'index', :name => 'Ruby' } %></div>
		<div class="col-md-2"><%= link_to "Java Items", { :controller => 'portfolios', :action => 'index', :name => 'Java' }%></div>
		<div class="col-md-2"></div>
	</div><br>
	<div class="card-group all-portfolios-card">
		<% @portfolio_items.each  do |item| %>
		<%= render partial: 'showPortfolioModal', locals: { itemid: item.id } %>


		<div class="col-md-4" style="width: 100%; height: 100%;">   
			<div class="card bg-white">
				<div class="card-body text-center">
					<div ><%= link_to image_tag(item.main_image.url, class: "portfolio-index-image" ), portfolio_path(item.id), :remote => true,'data-toggle' => 'modal', 'data-target' => '#myModalitems', :id =>'portfolio-id-{item.id}' %>
						
						 
					</div>
					<div><%= item.title %> </div>
					<div class="row">
						<div class="col-md-7"></div>
						<%if can? :edit, Portfolio%>
						<div class="col-md-2 icon-edit"> <%= link_to '<i class="far fa-edit fa-2x"></i>'.html_safe, edit_portfolio_path(item.id) %></div>
						<% end %>

						<% if can? :delete, Portfolio %>
						<div class="col-md-2 icon-delete"><%= link_to '<i class="fas fa-trash-alt fa-2x"></i>'.html_safe, "/portfolios/#{item.id}",method: :delete, data: {confirm: "Are you sure?"} %></div>
						<% end %>

						<div class="col-md-1"><%# link_to '<i class="far fa-eye fa-2x"></i>'.html_safe, portfolio_path(item.id) %></div>
					</div>
				</div>
			</div>
		</div>

		<% end %>
	</div>
</div>

app/views/portfolios/_showitemForAppend.html.erb
	<div class="card-group">
		<% @portfolio_items.each  do |item| %>
		<%= render partial: 'showPortfolioModal', locals: { itemid: item.id } %>


		<div class="col-md-4" style="width: 100%; height: 100%;">   
			<div class="card bg-white">
				<div class="card-body text-center">
					<div ><%= link_to image_tag(item.main_image.url, class: "portfolio-index-image" ), portfolio_path(item.id), :remote => true,'data-toggle' => 'modal', 'data-target' => '#myModalitems', :id =>'portfolio-id-{item.id}' %>
						
						 
					</div>
					<div><%= item.title %> </div>
					<div class="row">
						<div class="col-md-7"></div>
						<%if can? :edit, Portfolio%>
						<div class="col-md-2 icon-edit"> <%= link_to '<i class="far fa-edit fa-2x"></i>'.html_safe, edit_portfolio_path(item.id) %></div>
						<% end %>

						<% if can? :delete, Portfolio %>
						<div class="col-md-2 icon-delete"><%= link_to '<i class="fas fa-trash-alt fa-2x"></i>'.html_safe, "/portfolios/#{item.id}",method: :delete, data: {confirm: "Are you sure?"} %></div>
						<% end %>

						<div class="col-md-1"><%# link_to '<i class="far fa-eye fa-2x"></i>'.html_safe, portfolio_path(item.id) %></div>
					</div>
				</div>
			</div>
		</div>

		<% end %>
	</div>

app/views/portfolios/create.js.erb
// $('#myModal').modal('hide');

// $('#myModal').modal('hide');
// alert('hidden');

app/views/portfolios/edit.html.erb
<%= render "formportfolionew", portfolio_items: @portfolio_items %>
<!-- here portfolio_items is data from controller and @portfolio_item is instance variable 
for the partial form, by this way we can send daa in partial forms  -->

app/views/portfolios/index.html.erb
<div class="container">
	<div class="row" id="indexpage">
		<div class="col-md-1 " ></div>
		<div class="col-md-2" id="new-portfolio">
			<%#= link_to "Create new portfolio", new_portfolio_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg'} %>  <!--at the top it will create the create new item tag -->			
         <%= render 'newPortfolioModal'%>
		</div>
		<div class="col-md-9"></div>
	</div>
       <%= render 'showitem'%>
</div>

app/views/portfolios/new.html.erb
<div class="continer">
  <div class="card"><h1 style="text-align: center;" class="card-header"> New Portfolio item</h1>
   <%= render 'formportfolionew', portfolio_items: @portfolio_item %>
  <!-- partil form  -->
 </div>
</div>

app/views/portfolios/show.html.erb
 
 <%= image_tag  @portfolio_items.main_image.url(:large) %>
 <!--unless method is used to remove errors -->
 <h1><strong>
  <%= @portfolio_items.title %>
  </strong> </h1>
  <em><%= @portfolio_items.subtitle %> </em>
  <p>
  	<%= @portfolio_items.body %>
  </p>
  <h3> Technlogies Used:</h3>
  <% @portfolio_items.technlogies.each do |k| %>
    <h4><%= k.name %></h4>
  <% end %>
 <%= link_to 'Back', portfolios_path %><br><br>

app/views/portfolios/show.js.erb
$('#modal-header-portfolio-<%=@portfolio_items.id%>').replaceWith('<h3 class= "portfolio-modal-title"><%=  @portfolio_items.title  %></h3>');
$('#modal-body-subtitle-<%=@portfolio_items.id%>').replaceWith('<h4 class="subtitle-inside-modal"><%=  @portfolio_items.subtitle  %></h4>');
$('#modal-body-portfolio-<%=@portfolio_items.id%>').replaceWith('<%=  @portfolio_items.body %>');
$('#modal-image-portfolio-<%=@portfolio_items.id%>').replaceWith('<%= image_tag @portfolio_items.main_image.url, :size => "700x500", :crop => :fill, :class => "image-tag-in-portfolio-modal" %>');
$('#myModalitems-<%=@portfolio_items.id %>').modal('show')